//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response
    {
        public System.Guid ResponseId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.Guid> EventId { get; set; }
        public Nullable<bool> Response1 { get; set; }
    
        public virtual TeamEvent TeamEvent { get; set; }
        public virtual UserLogin UserLogin { get; set; }
    }
}
